name: release:trdl-release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  repository_dispatch:
    types: ["release:trdl-release"]
  workflow_dispatch:

jobs:
  release:
    name: Perform delivery-kit release
    runs-on: ubuntu-22.04
    steps:
#      - name: Notify
#        uses: mattermost/action-mattermost-notify@master
#        with:
#          MATTERMOST_WEBHOOK_URL: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
#          MATTERMOST_CHANNEL: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
#          TEXT: |
#            ${{ secrets.LOOP_NOTIFICATION_GROUP }} [${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) task sign pls

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get version from CHANGELOG.md
        id: get_version
        run: |
          VERSION=$(grep -m1 '^#\+ \[[0-9]\+\.[0-9]\+\.[0-9]\+\]' CHANGELOG.md | sed -E 's/^#+ \[([0-9]+\.[0-9]+\.[0-9]+)\].*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Generate notes.md
        id: notes
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          echo "## Changelog" > notes.md
          awk -v version="$VERSION" '
            $0 ~ "^#+ \\[" version "\\]" {capture=1; next}
            capture && $0 ~ "^#+ \\[" && $0 !~ "^#+ \\[" version "\\]" {exit}
            capture {print}
          ' CHANGELOG.md >> notes.md

          cat <<EOF >> notes.md
          ## Installation

          You can download \`delivery-kit\` binaries from here:
           * [Linux amd64](https://github.com/${{ github.repository }}/releases/download/v$VERSION/delivery-kit-linux-amd64)

          Example download on Linux:
          \`\`\`shell
          curl -sSLO "https://github.com/${{ github.repository }}/releases/download/v$VERSION/delivery-kit-linux-amd64"
          \`\`\`
          EOF

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.get_version.outputs.version }}" \
            --title "v${{ steps.get_version.outputs.version }}" \
            --prerelease \
            --notes-file notes.md

#  notify:
#    if: always()
#    needs: release
#    uses: werf/common-ci/.github/workflows/notification.yml@main
#    secrets:
#      loopNotificationGroup: ${{ secrets.LOOP_NOTIFICATION_GROUP }}
#      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
#      notificationChannel: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
